build:
    image: alpine:latest
    commands:
        - apk --no-cache add python py-pip ca-certificates py-psycopg2
        - pip install -r requirements.txt
        - pip install -r tests/requirements.txt
        - pip install -e .
        - py.test -v

notify:
  slack:
    webhook_url: $$ANTISMASH_SLACK_HOOK
    channel: general
    username: drone

  email:
    from: ci@secondarymetabolites.org
    host: mail.secondarymetabolites.org
    username: antismash
    password: $$ANTISMASH_EMAIL_PASSWORD
