build:
    image: alpine:latest
    commands:
        - apk --no-cache add python py-pip ca-certificates py-psycopg2 postgresql-client xz
        - pip install -r requirements.txt
        - pip install -r tests/requirements.txt
        - pip install -e .
        - echo "localhost:5432:*:postgres:secret" > ~/.pgpass
        - chmod 600 ~/.pgpass
        - psql -h localhost -U postgres -c 'CREATE DATABASE antismash'
        - xzcat tests/test.sql.xz | psql -h localhost -U postgres antismash > /dev/null
        - pytest -v

compose:
  database:
    image: postgres:9.4
    environmet:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

notify:
  slack:
    webhook_url: $$ANTISMASH_SLACK_HOOK
    channel: general
    username: drone

  email:
    from: ci@secondarymetabolites.org
    host: mail.secondarymetabolites.org
    username: antismash
    password: $$ANTISMASH_EMAIL_PASSWORD
