build:
    image: alpine:latest
    commands:
        - apk --no-cache add python py-pip ca-certificates py-psycopg2
        - pip install -r requirements.txt
        - pip install -r tests/requirements.txt
        - pip install -e .
        - py.test -v
